### ISSUE TITLE
Have source files?

### ISSUE THREAD

**Issue by AnterCreeper** [sukanka/KMREOnArch#2]
According to the copyright:

Format: http://dep.debian.net/deps/dep5/
Upstream-Name: kylin-kmre-window
Upstream-Contact: lixiang <lixiang@kylinos.cn>
Source: https://launchpad.dev/kylin-kmre-window

Files: *
Copyright: 2019-2021, Tianjin KYLIN Information Technology Co., Ltd..
License: GPL-3

License: GPL-3
 This package is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 3 of the License.
 .
 This package is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 .
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>
 .
 On Debian systems, the complete text of the GNU General
 Public License version 2 can be found in "/usr/share/common-licenses/GPL-3".

**Comment by sukanka** [comment]
I don't have source code, otherwise, I would compile it from source.
I have no access to  which https://launchpad.dev/kylin-kmre-window needs VISITOR PASSWORD.

**Comment by Jatin794** [comment]
This seems to be possible now.

https://gitee.com/openkylin/kylin-kmre-window

https://gitee.com/openkylin/kmre (probably relevant but it's just a readme in chinese)

**Comment by sukanka** [comment]
> This seems to be possible now.
> 
> https://gitee.com/openkylin/kylin-kmre-window
> 
> https://gitee.com/openkylin/kmre (probably relevant but it's just a readme in chinese)

Thanks for your notification, I'm now working on building them from source

**Comment by sukanka** [comment]
PKGBUILDs have been updated to build the packages from the source.
